//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WSApp.WebResources", typeof(WebResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map address.
        /// </summary>
        internal static string AboutAddress {
            get {
                return ResourceManager.GetString("AboutAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments.
        /// </summary>
        internal static string AboutComments {
            get {
                return ResourceManager.GetString("AboutComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact kurt@zighome.net..
        /// </summary>
        internal static string AboutContactMe {
            get {
                return ResourceManager.GetString("AboutContactMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Warm Showers Community is a free worldwide hospitality exchange for touring cyclists.  People who are willing to host touring cyclists sign up and provide their contact information, and may occasionally have someone stay with them and share great stories and a drink.  This mobile application is intended primarily for cyclists out on tour, to help them identify, locate, and coordinate with potential hosts..
        /// </summary>
        internal static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm Showers for Windows Phone was developed by Kurt Ziegler..
        /// </summary>
        internal static string AboutDevelopedBy {
            get {
                return ResourceManager.GetString("AboutDevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AboutGeneral {
            get {
                return ResourceManager.GetString("AboutGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about....
        /// </summary>
        internal static string aboutMenuText {
            get {
                return ResourceManager.GetString("aboutMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to call mobile.
        /// </summary>
        internal static string AboutPhone {
            get {
                return ResourceManager.GetString("AboutPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text (sms).
        /// </summary>
        internal static string AboutSMS {
            get {
                return ResourceManager.GetString("AboutSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view web site.
        /// </summary>
        internal static string AboutURL {
            get {
                return ResourceManager.GetString("AboutURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visit.
        /// </summary>
        internal static string AboutWeb {
            get {
                return ResourceManager.GetString("AboutWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aerial map.
        /// </summary>
        internal static string aerialViewMenuText {
            get {
                return ResourceManager.GetString("aerialViewMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ago.
        /// </summary>
        internal static string ago {
            get {
                return ResourceManager.GetString("ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can compose a message, edits will be saved.  Then go back and try sending again when connected to a network..
        /// </summary>
        internal static string AlertMessageFormNoNetwork {
            get {
                return ResourceManager.GetString("AlertMessageFormNoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can compose a message, edits will be saved.  Then go back, log in, and try sending again when connected to a network..
        /// </summary>
        internal static string AlertMessageFormNotLoggedIn {
            get {
                return ResourceManager.GetString("AlertMessageFormNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logged out.
        /// </summary>
        internal static string AlertNotLoggedIn {
            get {
                return ResourceManager.GetString("AlertNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apr.
        /// </summary>
        internal static string Apr {
            get {
                return ResourceManager.GetString("Apr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aug.
        /// </summary>
        internal static string Aug {
            get {
                return ResourceManager.GetString("Aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed.
        /// </summary>
        internal static string Bed {
            get {
                return ResourceManager.GetString("Bed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body cannot be blank.
        /// </summary>
        internal static string BodyBlank {
            get {
                return ResourceManager.GetString("BodyBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        internal static string by {
            get {
                return ResourceManager.GetString("by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to center on host location.
        /// </summary>
        internal static string centerHostContextMenuLabel {
            get {
                return ResourceManager.GetString("centerHostContextMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Warm Showers contact.
        /// </summary>
        internal static string ContactSubject {
            get {
                return ResourceManager.GetString("ContactSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send debug.
        /// </summary>
        internal static string debugButtonText {
            get {
                return ResourceManager.GetString("debugButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kurt@zighome.net.
        /// </summary>
        internal static string debugEmailAddress {
            get {
                return ResourceManager.GetString("debugEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debug mode is enabled.
        /// </summary>
        internal static string debugEnabled {
            get {
                return ResourceManager.GetString("debugEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turn on debug mode.
        /// </summary>
        internal static string debugMenuText {
            get {
                return ResourceManager.GetString("debugMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS debug.
        /// </summary>
        internal static string debugSubject {
            get {
                return ResourceManager.GetString("debugSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec.
        /// </summary>
        internal static string Dec {
            get {
                return ResourceManager.GetString("Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable use of location service..
        /// </summary>
        internal static string DisableLocationService {
            get {
                return ResourceManager.GetString("DisableLocationService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable use of location service..
        /// </summary>
        internal static string EnableLocationService {
            get {
                return ResourceManager.GetString("EnableLocationService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us on Facebook..
        /// </summary>
        internal static string FacebookFollow {
            get {
                return ResourceManager.GetString("FacebookFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/groups/135049549858210/.
        /// </summary>
        internal static string FacebookUri {
            get {
                return ResourceManager.GetString("FacebookUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feb.
        /// </summary>
        internal static string Feb {
            get {
                return ResourceManager.GetString("Feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filter.
        /// </summary>
        internal static string filterButtonText {
            get {
                return ResourceManager.GetString("filterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filtered.
        /// </summary>
        internal static string Filtered {
            get {
                return ResourceManager.GetString("Filtered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        internal static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from my location.
        /// </summary>
        internal static string FromCurrentLocation {
            get {
                return ResourceManager.GetString("FromCurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distance to nearest bike shop.
        /// </summary>
        internal static string HostingHeaderBikeShop {
            get {
                return ResourceManager.GetString("HostingHeaderBikeShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distance to nearest campgrnd.
        /// </summary>
        internal static string HostingHeaderCampground {
            get {
                return ResourceManager.GetString("HostingHeaderCampground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this host may offer.
        /// </summary>
        internal static string HostingHeaderHostMayOffer {
            get {
                return ResourceManager.GetString("HostingHeaderHostMayOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to languages spoken.
        /// </summary>
        internal static string HostingHeaderLanguagesSpoken {
            get {
                return ResourceManager.GetString("HostingHeaderLanguagesSpoken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum guests.
        /// </summary>
        internal static string HostingHeaderMaxCyclists {
            get {
                return ResourceManager.GetString("HostingHeaderMaxCyclists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distance to nearest hotel/motel.
        /// </summary>
        internal static string HostingHeaderMotel {
            get {
                return ResourceManager.GetString("HostingHeaderMotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preferred notice.
        /// </summary>
        internal static string HostingHeaderPreferred_notice {
            get {
                return ResourceManager.GetString("HostingHeaderPreferred_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid.
        /// </summary>
        internal static string invalid {
            get {
                return ResourceManager.GetString("invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        internal static string ItemGuest {
            get {
                return ResourceManager.GetString("ItemGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string ItemHost {
            get {
                return ResourceManager.GetString("ItemHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative.
        /// </summary>
        internal static string ItemNegative {
            get {
                return ResourceManager.GetString("ItemNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        internal static string ItemNeutral {
            get {
                return ResourceManager.GetString("ItemNeutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string ItemOther {
            get {
                return ResourceManager.GetString("ItemOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive.
        /// </summary>
        internal static string ItemPositive {
            get {
                return ResourceManager.GetString("ItemPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Met Traveling.
        /// </summary>
        internal static string ItemTraveling {
            get {
                return ResourceManager.GetString("ItemTraveling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan.
        /// </summary>
        internal static string Jan {
            get {
                return ResourceManager.GetString("Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jul.
        /// </summary>
        internal static string Jul {
            get {
                return ResourceManager.GetString("Jul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jun.
        /// </summary>
        internal static string Jun {
            get {
                return ResourceManager.GetString("Jun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of kitchen.
        /// </summary>
        internal static string Kitchen {
            get {
                return ResourceManager.GetString("Kitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        internal static string km {
            get {
                return ResourceManager.GetString("km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last access.
        /// </summary>
        internal static string LastAccess {
            get {
                return ResourceManager.GetString("LastAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laundry.
        /// </summary>
        internal static string Laundry {
            get {
                return ResourceManager.GetString("Laundry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawn space.
        /// </summary>
        internal static string LawnSpace {
            get {
                return ResourceManager.GetString("LawnSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to limit.
        /// </summary>
        internal static string limit {
            get {
                return ResourceManager.GetString("limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading....
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as.
        /// </summary>
        internal static string LoggedInAs {
            get {
                return ResourceManager.GetString("LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in.
        /// </summary>
        internal static string LoginMenuText {
            get {
                return ResourceManager.GetString("LoginMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to WarmShowers.org.
        /// </summary>
        internal static string LoginNew {
            get {
                return ResourceManager.GetString("LoginNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log out.
        /// </summary>
        internal static string LogoutMenuText {
            get {
                return ResourceManager.GetString("LogoutMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map.
        /// </summary>
        internal static string mapButtonText {
            get {
                return ResourceManager.GetString("mapButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar.
        /// </summary>
        internal static string Mar {
            get {
                return ResourceManager.GetString("Mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to me.
        /// </summary>
        internal static string me {
            get {
                return ResourceManager.GetString("me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to me.
        /// </summary>
        internal static string meButtonText {
            get {
                return ResourceManager.GetString("meButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member for.
        /// </summary>
        internal static string MemberFor {
            get {
                return ResourceManager.GetString("MemberFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        internal static string Memory {
            get {
                return ResourceManager.GetString("Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        internal static string mi {
            get {
                return ResourceManager.GetString("mi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the map to zoom out to a larger search area or to pan to a different location, or press the me button to search from the current location.  .
        /// </summary>
        internal static string NearbyListEmptyBody1 {
            get {
                return ResourceManager.GetString("NearbyListEmptyBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also, filters are active.  Clearing any filters may return hosts within the current search area..
        /// </summary>
        internal static string NearbyListEmptyBody2 {
            get {
                return ResourceManager.GetString("NearbyListEmptyBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map and me buttons are in the toolbar below..
        /// </summary>
        internal static string NearbyListEmptyBody3 {
            get {
                return ResourceManager.GetString("NearbyListEmptyBody3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no hosts were found.
        /// </summary>
        internal static string NearbyListEmptyHeader {
            get {
                return ResourceManager.GetString("NearbyListEmptyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To see nearby hosts, open the about... page and press &quot;Enable use of location service.&quot;.
        /// </summary>
        internal static string NearbyListLocationDisabledBody {
            get {
                return ResourceManager.GetString("NearbyListLocationDisabledBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location svc is disabled.
        /// </summary>
        internal static string NearbyListLocationDisabledHeader {
            get {
                return ResourceManager.GetString("NearbyListLocationDisabledHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new message.
        /// </summary>
        internal static string NewMessage {
            get {
                return ResourceManager.GetString("NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new message.
        /// </summary>
        internal static string NewMessageReceived {
            get {
                return ResourceManager.GetString("NewMessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new messages.
        /// </summary>
        internal static string NewMessages {
            get {
                return ResourceManager.GetString("NewMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new messages.
        /// </summary>
        internal static string NewMessagesReceived {
            get {
                return ResourceManager.GetString("NewMessagesReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no location.
        /// </summary>
        internal static string NoLocation {
            get {
                return ResourceManager.GetString("NoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no network.
        /// </summary>
        internal static string NoNetwork {
            get {
                return ResourceManager.GetString("NoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov.
        /// </summary>
        internal static string Nov {
            get {
                return ResourceManager.GetString("Nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct.
        /// </summary>
        internal static string Oct {
            get {
                return ResourceManager.GetString("Oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKButtonText {
            get {
                return ResourceManager.GetString("OKButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to panned.
        /// </summary>
        internal static string Panned {
            get {
                return ResourceManager.GetString("Panned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to peak.
        /// </summary>
        internal static string peak {
            get {
                return ResourceManager.GetString("peak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin.
        /// </summary>
        internal static string pin {
            get {
                return ResourceManager.GetString("pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pinned.
        /// </summary>
        internal static string pinned {
            get {
                return ResourceManager.GetString("pinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinned hosts appear here for quick, offline access.   To manually pin a host, select from the &apos;nearby&apos; list and press the &apos;pin&apos; button.  Hosts are automatically pinned when any of the following actions are taken from within the Warm Showers app:  contact or reply to a host, send a text, make a phone call, or map an address. .
        /// </summary>
        internal static string PinnedListEmptyBody {
            get {
                return ResourceManager.GetString("PinnedListEmptyBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also, a new private message will automatically pin the host from whom it was sent.  Press the update button in the toolbar below to check for new messages..
        /// </summary>
        internal static string PinnedListEmptyBody2 {
            get {
                return ResourceManager.GetString("PinnedListEmptyBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no hosts are pinned.
        /// </summary>
        internal static string PinnedListEmptyHeader {
            get {
                return ResourceManager.GetString("PinnedListEmptyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy: Location service is used to display nearby hosts..
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string RegisterButtonText {
            get {
                return ResourceManager.GetString("RegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/warmshowers/WarmShowers-Windows/blob/master/WarmShowers/WSWP7/Release%20History.md.
        /// </summary>
        internal static string RevisionsUri {
            get {
                return ResourceManager.GetString("RevisionsUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to road map.
        /// </summary>
        internal static string roadViewMenuText {
            get {
                return ResourceManager.GetString("roadViewMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAG.
        /// </summary>
        internal static string SAG {
            get {
                return ResourceManager.GetString("SAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        internal static string Salutation {
            get {
                return ResourceManager.GetString("Salutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        internal static string searchButtonText {
            get {
                return ResourceManager.GetString("searchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string second {
            get {
                return ResourceManager.GetString("second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sending feedback.
        /// </summary>
        internal static string SendingFeedback {
            get {
                return ResourceManager.GetString("SendingFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedback delivery failed.
        /// </summary>
        internal static string SendingFeedbackFailed {
            get {
                return ResourceManager.GetString("SendingFeedbackFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedback sent.
        /// </summary>
        internal static string SendingFeedbackSucceeded {
            get {
                return ResourceManager.GetString("SendingFeedbackSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body must be at least 10 words.
        /// </summary>
        internal static string SendingFeedbackTooShort {
            get {
                return ResourceManager.GetString("SendingFeedbackTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sending message.
        /// </summary>
        internal static string SendingMessage {
            get {
                return ResourceManager.GetString("SendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message delivery failed.
        /// </summary>
        internal static string SendingMessageFailed {
            get {
                return ResourceManager.GetString("SendingMessageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message sent.
        /// </summary>
        internal static string SendingMessageSucceeded {
            get {
                return ResourceManager.GetString("SendingMessageSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sending reply.
        /// </summary>
        internal static string SendingReply {
            get {
                return ResourceManager.GetString("SendingReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reply sent.
        /// </summary>
        internal static string SendingReplySucceeded {
            get {
                return ResourceManager.GetString("SendingReplySucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sent by.
        /// </summary>
        internal static string SentBy {
            get {
                return ResourceManager.GetString("SentBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sep.
        /// </summary>
        internal static string Sep {
            get {
                return ResourceManager.GetString("Sep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shower.
        /// </summary>
        internal static string Shower {
            get {
                return ResourceManager.GetString("Shower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose msg.  Try again..
        /// </summary>
        internal static string StatusNoNetwork {
            get {
                return ResourceManager.GetString("StatusNoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subject cannot be blank.
        /// </summary>
        internal static string SubjectBlank {
            get {
                return ResourceManager.GetString("SubjectBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this host may offer.
        /// </summary>
        internal static string ThisHostMayOffer {
            get {
                return ResourceManager.GetString("ThisHostMayOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Network.
        /// </summary>
        internal static string ToNoNetwork {
            get {
                return ResourceManager.GetString("ToNoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Logged In.
        /// </summary>
        internal static string ToNotLoggedIn {
            get {
                return ResourceManager.GetString("ToNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to see current traffic.
        /// </summary>
        internal static string trafficViewMenuText {
            get {
                return ResourceManager.GetString("trafficViewMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us on Twitter..
        /// </summary>
        internal static string TwitterFollow {
            get {
                return ResourceManager.GetString("TwitterFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/#!/warmshowers.
        /// </summary>
        internal static string TwitterUri {
            get {
                return ResourceManager.GetString("TwitterUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show distance in km.
        /// </summary>
        internal static string unitsMenuTextKm {
            get {
                return ResourceManager.GetString("unitsMenuTextKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show distance in mi.
        /// </summary>
        internal static string unitsMenuTextMi {
            get {
                return ResourceManager.GetString("unitsMenuTextMi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpin.
        /// </summary>
        internal static string unpin {
            get {
                return ResourceManager.GetString("unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update.
        /// </summary>
        internal static string updateButtonText {
            get {
                return ResourceManager.GetString("updateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://.
        /// </summary>
        internal static string uriPrefix {
            get {
                return ResourceManager.GetString("uriPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to used.
        /// </summary>
        internal static string used {
            get {
                return ResourceManager.GetString("used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view profile on warmshowers.org.
        /// </summary>
        internal static string viewHostMenuText {
            get {
                return ResourceManager.GetString("viewHostMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.warmshowers.org.
        /// </summary>
        internal static string WarmShowersUri {
            get {
                return ResourceManager.GetString("WarmShowersUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visit warmshowers.org.
        /// </summary>
        internal static string webSiteMenuText {
            get {
                return ResourceManager.GetString("webSiteMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week.
        /// </summary>
        internal static string week {
            get {
                return ResourceManager.GetString("week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks.
        /// </summary>
        internal static string weeks {
            get {
                return ResourceManager.GetString("weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        internal static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        internal static string years {
            get {
                return ResourceManager.GetString("years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you.
        /// </summary>
        internal static string you {
            get {
                return ResourceManager.GetString("you", resourceCulture);
            }
        }
    }
}
